### PR TITLE
Emit metrics via statsd

### PR DESCRIPTION
**Pull request by yuvipanda**
- Uses the statsd client library

### CODE REVIEW

**Comment by minrk** [comment]
This is awesome, thanks for getting this started @yuvipanda!

Things I'd like to track:

- spawn events (start, stop)
- login events
- spawn timing
- errors (HTTP and spawning)
- redirects (certain ones, anyway)

**Comment by yuvipanda** [comment]
I'm already tracking login events. Will add spawn timing and events shortly
:)

As for redirect and http errors - CHP statsd now counts response codes as
well - is that not enough?

On Thu, Mar 31, 2016 at 10:19 PM, Min RK <notifications@github.com> wrote:

> This is awesome, thanks for getting this started @yuvipanda
> <https://github.com/yuvipanda>!
>
> Things I'd like to track:
>
>    - spawn events (start, stop)
>    - login events
>    - spawn timing
>    - errors (HTTP and spawning)
>    - redirects (certain ones, anyway)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/jupyterhub/pull/499#issuecomment-204253000>
>



-- 
Yuvi Panda T
http://yuvi.in/blog

**Comment by minrk** [comment]
CHP for response codes is probably enough for now. At some point, I'd like to track specific redirects (from, to), which are indicative of problems when they happen too much.

**Comment by yuvipanda** [comment]
I've added some more fine grained redirect metrics for user spawning, but I think specific 'from' and 'to' ones shouldn't go into statsd but into logging.

**Comment by yuvipanda** [comment]
I think this is good enough for a first pass. I'll add more once this passes review and gets merged.

**Comment by rgbkrk** [comment]
This looks good, I'd say :shipit:

**Comment by minrk** [comment]
Thanks, @yuvipanda!

**Pull request merged**
