### PR TITLE
DEV: Allow configuration of default headers.

### PR DESCRIPTION
**Pull request by ssanderson**
Applies Content-Security-Policy: frame-ancestors 'self' by default.

### CODE REVIEW

**Comment by ssanderson** [comment]
ping @minrk @rgbkrk.  This is mostly copied from the jupyter_notebook implementation of the same functionality.

**Comment by minrk** [comment]
Makes sense. Looks like the test is failing due to the semicolon?

**Comment by ssanderson** [comment]
> Looks like the test is failing due to the semicolon?

Gah.  Fixed.

**Comment by rgbkrk** [comment]
Thanks, this is certainly good to have.

Would it make sense to expose a URI for logging CSP violations, as is done with the handler in the notebook server? CSP violations should be made known to an admin if they want to know.

**Pull request merged**
