### PR TITLE
add swagger spec for REST API

### PR DESCRIPTION
**Pull request by minrk**
See it [rendered here]( http://petstore.swagger.io/?url=https://raw.githubusercontent.com/minrk/jupyterhub/swagger-spec/docs/rest-api.yml#/default)

### CODE REVIEW

**Comment by willingc** [comment]
Nice! Travis is only failing on Python 3.3 which I don't think is necessary to support for docs.

**Comment by betatim** [comment]
It is failing on a return code being different for a call to the API. Seems
odd that this only fails one on platform and I don't think the commit has
anything to do with it. Heisenbug?

**Comment by minrk** [comment]
Yes, it's a Heisenbug. The test is specifically for special handling when something takes too long, so I'm guessing sometimes it actually finishes promptly. In any case, it's an intermittent bug in the tests, not the code.

**Comment by minrk** [comment]
It'll be interesting if we can render the swagger HTML into the sphinx docs on RTD. I'll look into the feasibility of that.

**Comment by willingc** [comment]
@minrk I was thinking the same thing. I will play around with it tomorrow too. When I looked this morning there were some swagger to markdown converters which might help. Though using it live via swagger is awesome and really what I would prefer as a developer.

**Comment by rgbkrk** [comment]
Love that swagger.

**Comment by willingc** [comment]
@rgbkrk Lol

**Comment by rgbkrk** [comment]
No seriously, I adore navigable API docs.

Ok, I *was* making a joke.

**Pull request merged**
