### PR TITLE
Post handler for  requesting authorization tokens; authenticated via form.

### PR DESCRIPTION
**Pull request by dominicfollett**

### CODE REVIEW

**Comment by minrk** [comment]
Great! Can you add a test that exercises this?

**Comment by dominicfollett** [comment]
Sure thing!

**Comment by minrk** [comment]
I don't see any problem with including this, just a bit of a challenge on my side of communicating that it will only work for a certain class of Authenticators. Thanks for the PR!

**Comment by dominicfollett** [comment]
Could you explain how to run tests locally? I tried looking at the travisci, but to no avail. I just want to make sure they pass locally before pushing onto a PR.

**Pull request merged**
