### PR TITLE
Allow specifying statsd host/port/prefix info

### PR DESCRIPTION
**Pull request by yuvipanda**
Currently only passes it through to CHP. This is needed
for the cases when JupyterHub spawns and maintains CHP.

### CODE REVIEW

**Comment by yuvipanda** [comment]
This is needed to actually use https://github.com/jupyter/configurable-http-proxy/pull/51 in the common case.

**Comment by yuvipanda** [comment]
The current test failures look like something that is just flaky timeout?

**Comment by willingc** [comment]
@yuvipanda I restarted Travis and it's now green.

I'll leave it for @minrk to review.

**Comment by yuvipanda** [comment]
@willingc thanks!

On Thu, Mar 31, 2016 at 2:58 AM, Carol Willing <notifications@github.com>
wrote:

> @yuvipanda <https://github.com/yuvipanda> I restarted Travis and it's now
> green.
>
> I'll leave it for @minrk <https://github.com/minrk> to review.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/jupyterhub/pull/496#issuecomment-203859114>
>



-- 
Yuvi Panda T
http://yuvi.in/blog

**Comment by minrk** [comment]
:+1: it would help in the future if you didn't commit the giant whitespace changes.

**Comment by yuvipanda** [comment]
hmm, my editor (atom) seems to be stripping empty lines with just
whitespace.

I guess the general attitude towards whitespace on blank lines is the same
as towards pep8, and I should just try to force atom to not strip
whitespace rather than strip trailing whitespace off all of the files?

This will affect everyone using atom though (it is the default setting),
and probably other editors.

On Thu, Mar 31, 2016 at 11:18 AM, Min RK <notifications@github.com> wrote:

> [image: :+1:] it would help in the future if you didn't commit the giant
> whitespace changes.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/jupyterhub/pull/496#issuecomment-204062878>
>



-- 
Yuvi Panda T
http://yuvi.in/blog

**Comment by yuvipanda** [comment]
and that default is unlikely to change:
https://github.com/atom/whitespace/issues/10

On Thu, Mar 31, 2016 at 11:21 AM, Yuvi Panda <yuvipanda@gmail.com> wrote:

> hmm, my editor (atom) seems to be stripping empty lines with just
> whitespace.
>
> I guess the general attitude towards whitespace on blank lines is the same
> as towards pep8, and I should just try to force atom to not strip
> whitespace rather than strip trailing whitespace off all of the files?
>
> This will affect everyone using atom though (it is the default setting),
> and probably other editors.
>
> On Thu, Mar 31, 2016 at 11:18 AM, Min RK <notifications@github.com> wrote:
>
>> [image: :+1:] it would help in the future if you didn't commit the giant
>> whitespace changes.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jupyter/jupyterhub/pull/496#issuecomment-204062878>
>>
>
>
>
> --
> Yuvi Panda T
> http://yuvi.in/blog
>



-- 
Yuvi Panda T
http://yuvi.in/blog

**Comment by minrk** [comment]
Yeah, atom's defaults are rude and quite annoying. I talked to them, and they agree that it's rude, but still want to impose their opinions on everyone. You can fix atom's defaults with settings > packages > whitespace > disable.

**Comment by yuvipanda** [comment]
cool. I've already done so.

I think documenting these kinda stylistic choices somewhere (I can't find
them in https://github.com/ipython/ipython/blob/master/CONTRIBUTING.md or
anywhere else) would help reduce friction for people coming in to
contribute who are used to contributing python code elsewhere. I still have
no idea what the actual conventions are, and seem to be accidentally
running into them one by one...

On Thu, Mar 31, 2016 at 1:39 PM, Min RK <notifications@github.com> wrote:

> Yeah, atom's defaults are rude and quite annoying. I talked to them, and
> they agree that it's rude, but still want to impose their opinions on
> everyone. You can fix atom's defaults with settings > packages > whitespace
> > disable.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/jupyterhub/pull/496#issuecomment-204116569>
>



-- 
Yuvi Panda T
http://yuvi.in/blog

**Comment by willingc** [comment]
@yuvipanda @minrk We discussed the at the Community Pipeline breakout yesterday increasing documentation to guide new contributors to the whitespace style. We're planning a Dev Guide, similar to the CPython devguide), that will provide better guidance for contributors on style.

**Comment by yuvipanda** [comment]
Thank you! That would be very useful :)

On Thu, Mar 31, 2016 at 4:40 PM, Carol Willing <notifications@github.com>
wrote:

> @yuvipanda <https://github.com/yuvipanda> @minrk
> <https://github.com/minrk> We discussed the at the Community Pipeline
> breakout yesterday increasing documentation to guide new contributors to
> the whitespace style. We're planning a Dev Guide, similar to the CPython
> devguide), that will provide better guidance for contributors on style.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/jupyterhub/pull/496#issuecomment-204176056>
>



-- 
Yuvi Panda T
http://yuvi.in/blog

**Comment by minrk** [comment]
Yup, that would be great. The main thing is that we aren't strict about style so strict style-imposing tools often produce extraneous changes.

**Pull request merged**
