### PR TITLE
Allow environment config values to be callable

### PR DESCRIPTION
**Pull request by yuvipanda**
This allows deployments to configure environment variables
that need to be different for each user / container (such as
credentials for various services, etc).

### CODE REVIEW

**Comment by yuvipanda** [comment]
These aren't coroutines, so should be pretty quick (in my install, it's just doing a HMAC - see https://github.com/yuvipanda/paws/blob/master/hub/jupyterhub_config.py#L29)

**Comment by minrk** [comment]
Something missing? This PR appears to be only whitespace changes.

**Comment by yuvipanda** [comment]
That's really weird - my first commit (
https://github.com/jupyter/jupyterhub/pull/497/commits/705ff787153290bad55dc4f888812451cfdb27b4)
has the changes, but the second commit somehow seems to have undone them?
I'll check and redo.

On Thu, Mar 31, 2016 at 10:15 PM, Min RK <notifications@github.com> wrote:

> Something missing? This PR appears to be only whitespace changes.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/jupyterhub/pull/497#issuecomment-204252028>
>



-- 
Yuvi Panda T
http://yuvi.in/blog

**Comment by yuvipanda** [comment]
@minrk fixed.

**Pull request merged**
