### PR TITLE
move non-persisted User objects (spawner-related) off of orm.User

### PR DESCRIPTION
**Pull request by minrk**
adds higher level User object, which handles spawning. This object has running, spawner, etc. attributes.

### CODE REVIEW

**Comment by ssanderson** [comment]
@minrk I'd like to take a look at this, but I'm not sure I'll have time to do a proper review in the next couple days (I'm scrambling to prep a bunch of stuff for [QuantCon](http://www.quantcon.com/) this weekend).  Is there a burning need to get this in soon apart from a desire to see JupyterHub v0.1?

**Comment by minrk** [comment]
@ssanderson not at all, this is just a proposal. Take your time. I cut 0.1 on Sunday, anyway.

**Comment by Carreau** [comment]
Doesn't seem to merge cleanly anymore. Should we close ?

**Comment by yuvipanda** [comment]
*bump*. Rebase or close?

**Comment by minrk** [comment]
I started rebasing, but had to move on to something else. I'll get around to finishing this soon, I hope.

**Comment by minrk** [comment]
Rebased, tests passing.

**Pull request merged**
