### PR TITLE
remove redundant use_subdomains

### PR DESCRIPTION
**Pull request by minrk**
non-empty subdomain_host is enough

### CODE REVIEW

**Comment by willingc** [comment]
@minrk Is there ever a case where subdomain_host was set to something and then for whatever reason is later set to None? I'm trying to reason through the cases (None, ' ', something) for subdomain_host.

**Comment by minrk** [comment]
No, there should only be two states:

- default (`''`)
- a string (subdomains are in use)

**Comment by willingc** [comment]
Excellent @minrk. The code looked good. Thanks for clarifying.

**Comment by willingc** [comment]
@minrk I'm going to go ahead and merge this since I think it will solve the Travis issue on #456

**Pull request merged**
