### PR TITLE
allow running single-user servers on subdomains

### PR DESCRIPTION
**Pull request by minrk**
relies on CHP's host-based routing (a feature I didn't add!)

requires wildcard DNS and wildcard SSL for a proper setup

### CODE REVIEW

**Comment by rgbkrk** [comment]
This is so great.

**Comment by willingc** [comment]
Very cool. Subdomains for class/lecture sections :+1:

**Comment by minrk** [comment]
Okay, I think everything's working, now. I just need to rig up some way to run the tests with the subdomain flag on via xip.io, and it should be good to go.

**Comment by minrk** [comment]
It works! Thanks to xip.io, it's even testing with (and without) subdomains on Travis.

**Comment by rgbkrk** [comment]
The xip tricks are so handy here.

**Comment by willingc** [comment]
Being able to test with xip is really nice.

**Pull request merged**
