### PR TITLE
Sphinx documentation that converts markdown using recommonmark

### PR DESCRIPTION
**Pull request by willingc**
@minrk Here's a first pass at using recommonmark to convert the markdown within Sphinx. There were some new updates on the rtd side for both recommonmark and commonmark.py today.

Highlights:
- doc-requirements.txt for now pins recommonmark
- conf.py adds a source parser section that uses recommonmark
- moved all docs into docs directory

### CODE REVIEW

**Comment by willingc** [comment]
@minrk I'm not sure commit 2815f722505c35eedea3b76c704ef238eb48f317 is needed. It did get Travis to pass the tests on Python 3.3.

**Comment by Carreau** [comment]
Nice !

Just note that for readthedocs you can also just make documentation using [mkdocs](http://www.mkdocs.org/)

**Comment by willingc** [comment]
@minrk If you like this, please merge since I don't have write access on the PR. 

@Carreau It looks as if readthedocs is leaning more toward recommonmark over mkdocs these days. Let's use recommonmark for now. We can always use mkdocs down the road if needed.

**Comment by minrk** [comment]
Merged, thanks!

**Comment by willingc** [comment]
Thanks @minrk. If you can grant me admin privileges on this repo, I can set up the RTD service in the Webhooks and Settings tab. Or if you feel more comfortable, I can ping you to add the setting once I have the RTD site set up.

**Comment by willingc** [comment]
@minrk If you could add me as an admin on the RTD project (https://readthedocs.org/projects/jupyterhub/), I would appreciate it :sunflower:

**Comment by Carreau** [comment]
> @minrk If you could add me as an admin on the RTD project (https://readthedocs.org/projects/jupyterhub/), I would appreciate it

Done.

**Comment by willingc** [comment]
@Carreau Thanks :sunny:

**Pull request merged**
